languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Micah Svenson"
# title = "Micah's Musings"
# logo = "/rocket_logo.png"
description = "Welcome to my personal website! Learn more about my career as a Software Engineer, my Mountain Biking hobby or checkout my blog -- Micah's Musings. I blog about things that interest me in the world of technology, space, and mountain biking."
# description = "Continuously Curious"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
   name = "Micah Svenson"
   image = "/profile.png"
   bio = "Continuously Curious"
   headline = "Software Engineer, Space Professional, and Mountain Biking Enthusiast"
   #headline = "Software Engineering, Space, Mountain Biking, and finding, much to my chagrin, that I care a lot about agile teams"
   #headline = "Software Engineer with a passion for space and mountain biking"
   links = [
     { github = "https://github.com/micah-svenson" },
     { linkedin = "https://linkedin.com/in/micah-svenson" },
   ]
